### PR TITLE
Fix fullName use case

### PR DESCRIPTION
**Pull request by Vanuan**
Fix for some concerns raised in #2

### CODE REVIEW

**Comment by Vanuan** [comment]
With this change and the following test case:

```
// test1.js
describe('test1', () => {
  it('is a duplicate test', () => {});
});

// test1-2.js
describe('test1', () => {
  it('is a duplicate test', () => {});
});

// test1-3.js
describe('test1', () => {
  it('is a unique test', () => {});
});

// test4.js
describe('test4', => {
  it('is a unique test', () => {})
})

// test5.js
describe('test5', () => {
  it('is a unique test', () => {})
})

```

I see only one duplicate test (which is a correct behavior but doesn't suit my use case)
```
Duplicate test names found:
File:  /__tests__/test/test1-2.js
Title:  test1 is a duplicate test
```

**Comment by Vanuan** [comment]
Well, actually, I thought it should show me both tests with a duplicate name, shouldn't it?

**Comment by palmerj3** [comment]
@Vanuan with a little modification it definitely could. I can take a look tomorrow morning and add that. But thank you SO MUCH for this PR and the conversation.

Sorry earlier for the confusion. I really do appreciate the contribution. Is this project something you'd want to collaborate on?

**Comment by palmerj3** [comment]
I published 1.1.0 with this

**Comment by Vanuan** [comment]
Well, I'm currently investigating flaky tests in my company's project.
One of the issues I found was copy pasted code (not changing test names when reusing code).
I'm also using `jasmineReporters.JUnitXmlReporter` to generate xml files which are parsed by Jenkins.
So when one test has failed the build became flaky: depending on whether the passing or the failing test was run last the test result was either fail or pass.

So I found two options:
1) Generating a unique filename using `modifyReportFileName` callback. It deemed impossible until I found something that you've done here: https://github.com/facebook/jest/pull/4594
2) Detecting unique filenames separately. This project doesn't help this use case so much as `fullName` here and `fullName` in `modifyReportFileName` are different for some reason. Probably jest groups fullName by a test filename so it must use the top-level describe for it.

**Comment by palmerj3** [comment]
Awesome! I work on very similar things at my company.

I wrote this for when we needed junit xml files for the same purpose. You might give it a shot. https://github.com/palmerj3/jest-junit

**Comment by palmerj3** [comment]
And if you'd like to collaborate on this project or another project (for a better solution) I'd love to do that.

**Pull request merged**
